create table uploaded_files (
    id bigint generated by default as identity primary key,
    file_type varchar(32) not null,
    original_filename varchar(255) not null,
    content_hash varchar(64) not null unique,
    processing_status varchar(32) not null,
    total_count integer not null default 0,
    valid_count integer not null default 0,
    error_count integer not null default 0,
    duplicate_count integer not null default 0,
    uploaded_at timestamp not null
);

create table external_transactions (
    id bigint generated by default as identity primary key,
    transaction_id varchar(80) not null unique,
    uploaded_file_id bigint not null references uploaded_files(id),
    transaction_type varchar(16) not null,
    original_transaction_id varchar(80),
    merchant_id varchar(80) not null,
    transaction_date date not null,
    amount decimal(19, 2) not null,
    masked_payment_number varchar(40) not null,
    partner_status varchar(24) not null,
    processing_status varchar(24) not null,
    created_at timestamp not null
);

create index idx_external_transactions_date on external_transactions(transaction_date);
create index idx_external_transactions_original on external_transactions(original_transaction_id);

create table validation_errors (
    id bigint generated by default as identity primary key,
    uploaded_file_id bigint not null references uploaded_files(id),
    row_number integer not null,
    transaction_id varchar(80),
    field_name varchar(80),
    error_code varchar(60) not null,
    error_message varchar(255) not null,
    created_at timestamp not null
);

create table ledger_entries (
    id bigint generated by default as identity primary key,
    ledger_reference_id varchar(80) not null unique,
    transaction_id varchar(80) not null unique,
    merchant_id varchar(80) not null,
    record_date date not null,
    amount decimal(19, 2) not null,
    ledger_status varchar(24) not null,
    created_at timestamp not null
);

create table reconciliation_results (
    id bigint generated by default as identity primary key,
    business_date date not null,
    transaction_id varchar(80) not null,
    external_transaction_id bigint references external_transactions(id),
    ledger_entry_id bigint references ledger_entries(id),
    result_type varchar(32) not null,
    compared_amount decimal(19, 2),
    executed_at timestamp not null
);

create index idx_reconciliation_results_date on reconciliation_results(business_date);

create table settlements (
    id bigint generated by default as identity primary key,
    business_date date not null unique,
    approval_amount decimal(19, 2) not null,
    cancellation_amount decimal(19, 2) not null,
    gross_amount decimal(19, 2) not null,
    fee_amount decimal(19, 2) not null,
    payout_amount decimal(19, 2) not null,
    settlement_status varchar(24) not null,
    confirmed_at timestamp not null
);

create table batch_executions (
    id bigint generated by default as identity primary key,
    job_name varchar(80) not null,
    business_date date,
    execution_status varchar(24) not null,
    processed_count integer not null default 0,
    error_message varchar(500),
    started_at timestamp not null,
    completed_at timestamp
);

create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(255) not null,
    user_role varchar(24) not null,
    active boolean not null default true,
    created_at timestamp not null
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    actor varchar(80) not null,
    action_type varchar(60) not null,
    target_type varchar(60) not null,
    target_id varchar(100),
    metadata varchar(1000),
    occurred_at timestamp not null
);
